// Autogenerated by SHomeDSL
package rise.smarthome.model.devices;

public class AutomaticWindow extends Actuator {

	public AutomaticWindow(int pin, boolean isAnalog) {
		super(pin, isAnalog,"Automatic Window");
 	}
        @Override
	public String toString() {
		return "Automatic Window [state=" + getState() + ", pin=" + getPin()+ "]";
	}
}