// Autogenerated by SHomeDSL
package rise.smarthome.model.devices;

public class PresenceSensor extends Sensor {

	public PresenceSensor(int pin, boolean isAnalog) {
		super(pin, isAnalog,"Presence Sensor");
 	}
        @Override
	public String toString() {
		return ""Presence Sensor" [state=" + getState() + ", pin=" + getPin()+ "]";
	}
}