// Autogenerated by SHomeDSL
package rise.smarthome.model.devices;

public class TemperatureSensor extends Sensor {

	public TemperatureSensor(int pin, boolean isAnalog) {
		super(pin, isAnalog,"Temperature Sensor");
 	}

    @Override
	protected int[] activationValues() {
		return ListUtils.createArrayRange(0, 100);
	}
}