// Autogenerated by SHomeDSL
package rise.smarthome.model.devices;

public class TemperatureSensor extends Sensor {

	public TemperatureSensor(int pin, boolean isAnalog) {
		super(pin, isAnalog,"bu");
 	}
        @Override
	public String toString() {
		return "bu [state=" + getState() + ", pin=" + getPin()+ "]";
	}
}