// Autogenerated by SHomeDSL
package {{systemName|lower}}.smarthome.model.devices;

public class {{data.device.entity}} extends {{data.device.typeDevice}} {

	public {{data.device.entity}}(int pin, boolean isAnalog) {
		super(pin, isAnalog,{% if data.device.alias %}"{{data.device.alias}}"{% else %}"{{data.device.entity|splitName}}"{% endif %});
 	}
        @Override
	public String toString() {
		return "{% if data.device.alias %}"{{data.device.alias}}"{% else %}"{{data.device.entity|splitName}}"{% endif %} [state=" + getState() + ", pin=" + getPin()+ "]";
	}
}