// Autogenerated by SHomeDSL
package {{systemName|lower}}.smarthome.model.devices;

public class {{data.device.name}} extends {{data.device.typeDevice}} {

	public {{data.device.name}}(int pin, boolean isAnalog) {
		super(pin, isAnalog,{% if data.device.alias %}"{{data.device.alias}}"{% else %}"{{data.device.name|splitName}}"{% endif %});
 	}
        @Override
	public String toString() {
		return "{% if data.device.alias %}{{data.device.alias}}{% else %}{{data.device.name|splitName}}{% endif %} [state=" + getState() + ", pin=" + getPin()+ "]";
	}
}